const MEMSWAP_ABI = [
  { inputs: [], stateMutability: 'nonpayable', type: 'constructor' },
  { inputs: [], name: 'IntentAlreadyFulfilled', type: 'error' },
  { inputs: [], name: 'IntentExpired', type: 'error' },
  { inputs: [], name: 'IntentNotFulfilled', type: 'error' },
  { inputs: [], name: 'InvalidSignature', type: 'error' },
  { inputs: [], name: 'Unauthorized', type: 'error' },
  { inputs: [], name: 'UnsuccessfullCall', type: 'error' },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'bytes32',
        name: 'intentHash',
        type: 'bytes32',
      },
      {
        components: [
          { internalType: 'address', name: 'maker', type: 'address' },
          { internalType: 'address', name: 'filler', type: 'address' },
          { internalType: 'contract IERC20', name: 'tokenIn', type: 'address' },
          {
            internalType: 'contract IERC20',
            name: 'tokenOut',
            type: 'address',
          },
          { internalType: 'address', name: 'referrer', type: 'address' },
          { internalType: 'uint32', name: 'referrerFeeBps', type: 'uint32' },
          {
            internalType: 'uint32',
            name: 'referrerSurplusBps',
            type: 'uint32',
          },
          { internalType: 'uint32', name: 'deadline', type: 'uint32' },
          { internalType: 'uint128', name: 'amountIn', type: 'uint128' },
          { internalType: 'uint128', name: 'startAmountOut', type: 'uint128' },
          {
            internalType: 'uint128',
            name: 'expectedAmountOut',
            type: 'uint128',
          },
          { internalType: 'uint128', name: 'endAmountOut', type: 'uint128' },
          { internalType: 'bytes', name: 'signature', type: 'bytes' },
        ],
        indexed: false,
        internalType: 'struct Memswap.Intent',
        name: 'intent',
        type: 'tuple',
      },
    ],
    name: 'IntentFulfilled',
    type: 'event',
  },
  {
    inputs: [],
    name: 'DOMAIN_SEPARATOR',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'ORDER_TYPEHASH',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'filler', type: 'address' },
      { internalType: 'bytes32', name: 'intentHash', type: 'bytes32' },
    ],
    name: 'delegate',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'address', name: 'maker', type: 'address' },
          { internalType: 'address', name: 'filler', type: 'address' },
          { internalType: 'contract IERC20', name: 'tokenIn', type: 'address' },
          {
            internalType: 'contract IERC20',
            name: 'tokenOut',
            type: 'address',
          },
          { internalType: 'address', name: 'referrer', type: 'address' },
          { internalType: 'uint32', name: 'referrerFeeBps', type: 'uint32' },
          {
            internalType: 'uint32',
            name: 'referrerSurplusBps',
            type: 'uint32',
          },
          { internalType: 'uint32', name: 'deadline', type: 'uint32' },
          { internalType: 'uint128', name: 'amountIn', type: 'uint128' },
          { internalType: 'uint128', name: 'startAmountOut', type: 'uint128' },
          {
            internalType: 'uint128',
            name: 'expectedAmountOut',
            type: 'uint128',
          },
          { internalType: 'uint128', name: 'endAmountOut', type: 'uint128' },
          { internalType: 'bytes', name: 'signature', type: 'bytes' },
        ],
        internalType: 'struct Memswap.Intent',
        name: 'intent',
        type: 'tuple',
      },
      { internalType: 'address', name: 'fillContract', type: 'address' },
      { internalType: 'bytes', name: 'fillData', type: 'bytes' },
    ],
    name: 'execute',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'address', name: 'maker', type: 'address' },
          { internalType: 'address', name: 'filler', type: 'address' },
          { internalType: 'contract IERC20', name: 'tokenIn', type: 'address' },
          {
            internalType: 'contract IERC20',
            name: 'tokenOut',
            type: 'address',
          },
          { internalType: 'address', name: 'referrer', type: 'address' },
          { internalType: 'uint32', name: 'referrerFeeBps', type: 'uint32' },
          {
            internalType: 'uint32',
            name: 'referrerSurplusBps',
            type: 'uint32',
          },
          { internalType: 'uint32', name: 'deadline', type: 'uint32' },
          { internalType: 'uint128', name: 'amountIn', type: 'uint128' },
          { internalType: 'uint128', name: 'startAmountOut', type: 'uint128' },
          {
            internalType: 'uint128',
            name: 'expectedAmountOut',
            type: 'uint128',
          },
          { internalType: 'uint128', name: 'endAmountOut', type: 'uint128' },
          { internalType: 'bytes', name: 'signature', type: 'bytes' },
        ],
        internalType: 'struct Memswap.Intent',
        name: 'intent',
        type: 'tuple',
      },
    ],
    name: 'getIntentHash',
    outputs: [{ internalType: 'bytes32', name: 'intentHash', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    name: 'isDelegated',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    name: 'isFulfilled',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  { stateMutability: 'payable', type: 'receive' },
]

const WETH_ABI = [
  {
    constant: true,
    inputs: [],
    name: 'name',
    outputs: [{ name: '', type: 'string' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
  },
  {
    constant: false,
    inputs: [
      { name: 'guy', type: 'address' },
      { name: 'wad', type: 'uint256' },
    ],
    name: 'approve',
    outputs: [{ name: '', type: 'bool' }],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    constant: true,
    inputs: [],
    name: 'totalSupply',
    outputs: [{ name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
  },
  {
    constant: false,
    inputs: [
      { name: 'src', type: 'address' },
      { name: 'dst', type: 'address' },
      { name: 'wad', type: 'uint256' },
    ],
    name: 'transferFrom',
    outputs: [{ name: '', type: 'bool' }],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    constant: false,
    inputs: [{ name: 'wad', type: 'uint256' }],
    name: 'withdraw',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    constant: true,
    inputs: [],
    name: 'decimals',
    outputs: [{ name: '', type: 'uint8' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
  },
  {
    constant: true,
    inputs: [{ name: '', type: 'address' }],
    name: 'balanceOf',
    outputs: [{ name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
  },
  {
    constant: true,
    inputs: [],
    name: 'symbol',
    outputs: [{ name: '', type: 'string' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
  },
  {
    constant: false,
    inputs: [
      { name: 'dst', type: 'address' },
      { name: 'wad', type: 'uint256' },
    ],
    name: 'transfer',
    outputs: [{ name: '', type: 'bool' }],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    constant: false,
    inputs: [],
    name: 'deposit',
    outputs: [],
    payable: true,
    stateMutability: 'payable',
    type: 'function',
  },
  {
    constant: true,
    inputs: [
      { name: '', type: 'address' },
      { name: '', type: 'address' },
    ],
    name: 'allowance',
    outputs: [{ name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
  },
  { payable: true, stateMutability: 'payable', type: 'fallback' },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'src', type: 'address' },
      { indexed: true, name: 'guy', type: 'address' },
      { indexed: false, name: 'wad', type: 'uint256' },
    ],
    name: 'Approval',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'src', type: 'address' },
      { indexed: true, name: 'dst', type: 'address' },
      { indexed: false, name: 'wad', type: 'uint256' },
    ],
    name: 'Transfer',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'dst', type: 'address' },
      { indexed: false, name: 'wad', type: 'uint256' },
    ],
    name: 'Deposit',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'src', type: 'address' },
      { indexed: false, name: 'wad', type: 'uint256' },
    ],
    name: 'Withdrawal',
    type: 'event',
  },
]

export { MEMSWAP_ABI, WETH_ABI }
